services:
  - type: web
    name: video-labeling-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GCS_BUCKET
        value: openvision_labelling_service
    healthCheckPath: /api/health 